import Head from "next/head";
import Ads from "../components/Ads";
import About from "../components/About";
import Navbar from "../components/Navbar";
import BackgroundImg from "../components/BackgroundImg";
import SearchBar from "../components/SearchBar";
import AirbnbIntroducing from "../components/AirbnbIntroducing";
import ExploreNearby from "../components/ExploreNearby";
import LiveAnywhere from "../components/LiveAnywhere";
import TheGreatest from "../components/TheGreatest";
import DiscoverExperiences from "../components/DiscoverExperiences";
import BecomeHost from "../components/BecomeHost";
import InspirationFuture from "../components/InspirationFuture";
import Footer from "../components/Footer";
import { useEffect, useState } from "react";

export default function Home() {
    const [colorChange, setColorchange] = useState(false);

    useEffect(() => {
        const changeNavbarColor = () => {
            if (window.scrollY >= 50) {
                setColorchange(true);
            } else {
                setColorchange(false);
            }
        };
        window.addEventListener("scroll", changeNavbarColor);
        return () => removeEventListener(changeNavbarColor);
    }, []);
    return (
        <div>
            <Head>
                <title>Airbnb Fake</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="max-w-screen-3xl h-screen relative mx-auto">
                {" "}
                {/*overflow-x-hidden*/}
                <div>
                    <div>
                        <Ads />
                        <BackgroundImg />
                        <Navbar colorChange={colorChange} />
                        <SearchBar visibility={colorChange} />
                        <AirbnbIntroducing visibility={colorChange} />
                    </div>
                </div>
                <main className="relative z-20 mt-40">
                    <About />
                    <ExploreNearby />
                    <LiveAnywhere />
                    <TheGreatest />
                    <DiscoverExperiences />
                    <BecomeHost />
                    <InspirationFuture />
                </main>
                <footer className="mt-10 border-t ">
                    <Footer />
                </footer>
            </div>
        </div>
    );
}
